version: "3"

services:
  mongodb:
    build:
      context: ./bins/mongodb
    container_name: "${COMPOSE_PROJECT_NAME}-mongodb"
    restart: "always"
    ports:
      - "127.0.0.1:${HOST_MACHINE_MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
    external: true
    name: ${NETWORK_NAME}
