version: "3"

services:
  php82:
    build:
      context: ./bins/php82
    container_name: "${COMPOSE_PROJECT_NAME}-php82"
    restart: "always"
    ports:
      - "0.0.0.0:${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      # - "0.0.0.0:${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - "0.0.0.0:${HOST_MACHINE_SECURE_HOST_PORT}:9000"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html:rw
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
      - ${SSL_DIR-./config/ssl}:/etc/apache2/ssl/
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=0.0.0.0 remote_port=${XDEBUG_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
    external: true
    name: ${NETWORK_NAME}
